=== dante-compass/dante-engine/engine-core/core-foundation/src/main/resources/antisamy/antisamy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="anti-samy-rules">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="include" type="Include" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="directives" type="Directives"/>
				<xsd:element name="common-regexps" type="CommonRegexps"/>
				<xsd:element name="common-attributes" type="AttributeList"/>
				<xsd:element name="global-tag-attributes" type="AttributeList"/>
				<xsd:element name="dynamic-tag-attributes" type="AttributeList" minOccurs="0"/>
				<xsd:element name="tags-to-encode" type="TagsToEncodeList" minOccurs="0"/>
				<xsd:element name="tag-rules" type="TagRules"/>
				<xsd:element name="css-rules" type="CSSRules"/>
				<xsd:element name="allowed-empty-tags" type="LiteralListTag" minOccurs="0"/>
				<xsd:element name="require-closing-tags" type="LiteralListTag" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Include">
		<xsd:attribute name="href" use="required" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Directives">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="directive" type="Directive" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Directive">
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="value" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="CommonRegexps">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="regexp" type="RegExp" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="AttributeList">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="attribute" type="Attribute" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="TagsToEncodeList">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="tag" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="TagRules">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="tag" type="Tag" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Tag">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="attribute" type="Attribute" minOccurs="0" />
		</xsd:sequence>
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="action" use="required"/>
	</xsd:complexType>

    <xsd:complexType name="LiteralListTag">
        <xsd:sequence>
            <xsd:element name="literal-list" type="LiteralList" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

	<xsd:complexType name="Attribute">
		<xsd:sequence>
			<xsd:element name="regexp-list" type="RegexpList" minOccurs="0"/>
			<xsd:element name="literal-list" type="LiteralList" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="description"/>
		<xsd:attribute name="onInvalid"/>
	</xsd:complexType>

	<xsd:complexType name="RegexpList">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="regexp" type="RegExp" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="RegExp">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="LiteralList">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="literal" type="Literal" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Literal">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="CSSRules">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="property" type="Property" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Property">
		<xsd:sequence>
			<xsd:element name="urlCategory-list" type="CategoryList" minOccurs="0"/>
			<xsd:element name="literal-list" type="LiteralList" minOccurs="0"/>
			<xsd:element name="regexp-list" type="RegexpList" minOccurs="0"/>
			<xsd:element name="shorthand-list" type="ShorthandList" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="default" type="xsd:string"/>
		<xsd:attribute name="description" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="ShorthandList">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="shorthand" type="Shorthand" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Shorthand">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="CategoryList">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="urlCategory" type="Category" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Category">
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Entity">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="cdata" type="xsd:string" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== dante-compass/dante-engine/dante-framework/dante-spring/src/main/resources/antisamy/antisamy-anythinggoes.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>


<!--
  ~ DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  ~
  ~ Copyright (c) 2020-2030 ??? ZHENGGENGWEI (???), <herodotus@aliyun.com> Licensed under the AGPL License
  ~
  ~ This file is part of Herodotus Stirrup.
  ~
  ~ Herodotus Stirrup is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published
  ~ by the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Herodotus Stirrup is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <https://www.herodotus.cn>.
  -->


<!-- W3C rules retrieved from: http://www.w3.org/TR/html401/struct/global.html -->


<anti-samy-rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="antisamy.xsd">

    <directives>
        <directive name="omitXmlDeclaration" value="true" />
        <directive name="omitDoctypeDeclaration" value="true" />
        <directive name="maxInputSize" value="200000" />
        <directive name="formatOutput" value="true" />
        <directive name="noopenerAndNoreferrerAnchors" value="true"/>

        <!-- remember, this won't work for relative URIs - AntiSamy doesn't know anything about the URL or your web structure -->
        <directive name="embedStyleSheets" value="false" />
        <directive name="connectionTimeout" value="5000" />
        <directive name="maxStyleSheetImports" value="3" />

    </directives>

    <common-regexps>

        <!-- From W3C: This attribute assigns a class name or set of class names to an element. Any number of elements may be assigned the same 
            class name or names. Multiple class names must be separated by white space characters. -->

        <!-- The 16 colors defined by the HTML Spec (also used by the CSS Spec) -->
        <regexp name="colorName"
            value="(aqua|black|blue|fuchsia|gray|grey|green|lime|maroon|navy|olive|purple|red|silver|teal|white|yellow)" />

        <!-- HTML/CSS Spec allows 3 or 6 digit hex to specify color -->
        <regexp name="colorCode" value="(#([0-9a-fA-F]{6}|[0-9a-fA-F]{3}))" />

        <regexp name="anything" value=".*" />
        <regexp name="numberOrPercent" value="(\d)+(%{0,1})" />
        <regexp name="paragraph" value="[\p{L}\p{N},'.\s\-_\(\)&amp;;]*" />
        <regexp name="htmlId" value="[a-zA-Z0-9\:\-_\.]+" />
        <regexp name="htmlTitle" value="[\p{L}\p{N}\s\-_',:\[\]!\./\\\(\)&amp;]*" /> <!-- force non-empty with a '+' at the end instead of '*' -->
        <regexp name="htmlClass" value="[a-zA-Z0-9\s,\-_]+" />

        <regexp name="onsiteURL"
            value="^(?!//)(?![\p{L}\p{N}\\\.\#@\$%\+&amp;;\-_~,\?=/!]*(&amp;colon))[\p{L}\p{N}\\\.\#@\$%\+&amp;;\-_~,\?=/!]*" />
        <regexp name="offsiteURL"
            value="(\s)*((ht|f)tp(s?)://|mailto:)[\p{L}\p{N}]+[\p{L}\p{N}\p{Zs}\.\#@\$%\+&amp;;:\-_~,\?=/!\(\)]*(\s)*" />

        <regexp name="boolean" value="(true|false)" />
        <regexp name="singlePrintable" value="[a-zA-Z0-9]{1}" /> <!-- \w allows the '_' character -->

        <!-- This is for elements (ex: elemName { ... }) -->
        <regexp name="cssElementSelector" value="[a-zA-Z0-9-_]+|\*" />

        <!-- This is to list out any element names that are *not* valid -->
        <regexp name="cssElementExclusion" value="" />

        <!-- This if for classes (ex: .className { ... }) -->
        <regexp name="cssClassSelector" value="\.[a-zA-Z0-9-_]+" />

        <!-- This is to list out any class names that are *not* valid -->
        <regexp name="cssClassExclusion" value="" />

        <!-- This is for ID selectors (ex: #myId { ... } -->
        <regexp name="cssIDSelector" value="#[a-zA-Z0-9-_]+" />

        <!-- This is to list out any IDs that are *not* valid - FIXME: What should the default be to avoid div hijacking? *? -->
        <regexp name="cssIDExclusion" value="" />

        <!-- This is for pseudo-element selector (ex. foo:pseudo-element { ... } -->
        <regexp name="cssPseudoElementSelector" value=":[a-zA-Z0-9\-_]+" />

        <!-- This is to list out any pseudo-element names that are *not* valid -->
        <regexp name="cssPseudoElementExclusion" value="" />

        <!-- This is for attribute selectors (ex. foo[attr=value] { ... } -->
        <regexp name="cssAttributeSelector" value="\[[a-zA-Z0-9\-_]+((=|~=|\|=){1}[a-zA-Z0-9\-_]+){1}\]" />

        <!-- This is to list out any attribute names that are *not* valid -->
        <regexp name="cssAttributeExclusion" value="" />

        <!-- This is for resources referenced from CSS (such as background images and other imported stylesheets) -->
        <regexp name="cssOnsiteUri" value="url\(([\p{L}\p{N}\\/\.\?=\#&amp;;\-_~]+|\#(\w)+)\)" />
        <regexp name="cssOffsiteUri"
            value="url\((\s)*((ht|f)tp(s?)://)[\p{L}\p{N}]+[~\p{L}\p{N}\p{Zs}\-_\.@#$%&amp;;:,\?=/\+!]*(\s)*\)" />

        <!-- This if for CSS Identifiers -->
        <regexp name="cssIdentifier" value="[a-zA-Z0-9\-_]+" />

        <!-- This is for comments within CSS (ex. /* comment */) -->
        <regexp name="cssCommentText" value="[\p{L}\p{N}\-_,\/\\\.\s\(\)!\?\=\$#%\^&amp;:&quot;']+" />

        <regexp name="integer" value="(-|\+)?[0-9]+" />
        <regexp name="positiveInteger" value="(\+)?[0-9]+" />
        <regexp name="number" value="(-|\+)?([0-9]+(\.[0-9]+)?)" />
        <regexp name="angle" value="(-|\+)?([0-9]+(\.[0-9]+)?)(deg|grad|rad)" />
        <regexp name="time" value="([0-9]+(\.[0-9]+)?)(ms|s)" />
        <regexp name="frequency" value="([0-9]+(\.[0-9]+)?)(hz|khz)" />
        <regexp name="length" value="((-|\+)?0|(-|\+)?([0-9]+(\.[0-9]+)?([eE][+-]?[0-9]+)?)(rem|vw|vh|em|ex|px|in|cm|mm|pt|pc))" />
        <regexp name="positiveLength" value="((\+)?0|(\+)?([0-9]+(\.[0-9]+)?([eE][+-]?[0-9]+)?)(rem|vw|vh|em|ex|px|in|cm|mm|pt|pc))" />
        <regexp name="percentage" value="(-|\+)?([0-9]+(\.[0-9]+)?)%" />
        <regexp name="positivePercentage" value="(\+)?([0-9]+(\.[0-9]+)?)%" />
        <regexp name="ratio" value="[0-9]+/[0-9]+"/>
        <regexp name="resolution" value="((\+)?0|(\+)?([0-9]+(\.[0-9]+)?)(dpi|dpcm|dppx|x))"/>

        <regexp name="absolute-size" value="(xx-small|x-small|small|medium|large|x-large|xx-large)" />
        <regexp name="relative-size" value="(larger|smaller)" />

        <!-- Used for CSS Color specifications (complex regexp expresses integer values of 0-255) -->
        <regexp name="rgbCode"
            value="rgb\(([1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]),([1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]),([1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])\)" />

        <!-- CSS2 Allowed System Color Values -->
        <regexp name="systemColor"
            value="(activeborder|activecaption|appworkspace|background|buttonface|buttonhighlight|buttonshadow|buttontext|captiontext|graytext|highlight|highlighttext|inactiveborder|inactivecaption|inactivecaptiontext|infobackground|infotext|menu|menutext|scrollbar|threeddarkshadow|threedface|threedhighlight|threedlightshadow|threedshadow|window|windowframe|windowtext)" />

    </common-regexps>

    <!-- Tag.name = a, b, div, body, etc. Tag.action = filter: remove tags, but keep content, validate: keep content as long as it passes rules, 
        remove: remove tag and contents Attribute.name = id, class, href, align, width, etc. Attribute.onInvalid = what to do when the attribute is invalid, 
        e.g., remove the tag (removeTag), remove the attribute (removeAttribute), filter the tag (filterTag) Attribute.description = What rules in English 
        you want to tell the users they can have for this attribute. Include helpful things so they'll be able to tune their HTML -->

    <!-- Some attributes are common to all (or most) HTML tags. There aren't many that qualify for this. You have to make sure there's no collisions 
        between any of these attribute names with attribute names of other tags that are for different purposes. -->

    <common-attributes>


        <!-- Common to all HTML tags -->

        <attribute name="id" description="The 'id' of any HTML attribute should not contain anything besides letters and numbers">
            <regexp-list>
                <regexp name="htmlId" />
            </regexp-list>
        </attribute>

        <attribute name="class"
            description="The 'class' of any HTML attribute is usually a single word, but it can also be a list of class names separated by spaces">
            <regexp-list>
                <regexp name="htmlClass" />
            </regexp-list>
        </attribute>

        <attribute name="lang"
            description="The 'lang' attribute tells the browser what language the element's attribute values and content are written in">
            <regexp-list>
                <regexp value="[a-zA-Z0-9-]{2,20}" />
            </regexp-list>
        </attribute>
        <attribute name="title"
            description="The 'title' attribute provides text that shows up in a 'tooltip' when a user hovers their mouse over the element">
            <regexp-list>
                <regexp name="htmlTitle" />
            </regexp-list>
        </attribute>

        <attribute name="alt"
            description="The 'alt' attribute provides alternative text to users when its visual representation is not available">
            <regexp-list>
                <regexp name="paragraph" />
            </regexp-list>
        </attribute>


        <!-- the "style" attribute will be validated by an inline stylesheet scanner, so no need to define anything here - i hate having to special 
            case this but no other choice -->
